### PR TITLE
get the config before update

### LINKED ISSUE #212: Update cr failed due to the object has been modified
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Sometimes, we encountered some **operation cannot be fulfilled** errors when we updated the cr, the cause of this error is this cr has been modified by other processes.
```console
E0313 22:40:44.011546   10826 reconcile_operand.go:320] Fail to update status
E0313 22:40:44.011574   10826 reconcile_operand.go:282] Failed to create custom resource: Operation cannot be fulfilled on operandconfigs.operator.ibm.com "common-service": the object has been modified; please apply your changes to the latest version and try again
E0313 22:40:44.011591   10826 reconcile_operand.go:74] Error when get create or update custom resource: Operand reconcile error list : Operation cannot be fulfilled on operandconfigs.operator.ibm.com "common-service": the object has been modified; please apply your changes to the latest version and try again
```
**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- ODLM version:
- Minikube/KIND/OCP version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by horis233**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #212 

When ODLM updates the operand status, get the last instance first then update operand status.
**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

File: pkg/controller/operandrequest/config_status.go [hunk 1]
```diff
@@ -27,8 +27,13 @@ import (
 func (r *ReconcileOperandRequest) updateServiceStatus(cr *operatorv1alpha1.OperandConfig, operatorName, serviceName string, serviceStatus operatorv1alpha1.ServicePhase) error {
 	klog.V(3).Info("Updating OperandConfig status")
 
-	cr.Status.ServiceStatus[operatorName].CrStatus[serviceName] = serviceStatus
-	if err := r.client.Status().Update(context.TODO(), cr); err != nil {
+	configInstance, err := r.getConfigInstance(cr.Name, cr.Namespace)
```
Comment (DanielXLee) [inline pkg/controller/operandrequest/config_status.go]: @horis233 maybe we can add a wait logic until update success, you can followhttps://github.com/IBM/operand-deployment-lifecycle-manager/blob/e1467d496a45bf46d3551ecd676840160fd32fe9/test/helpers/helpers.go#L179

Comment (horis233) [reply pkg/controller/operandrequest/config_status.go]: @DanielXLee Thanks, I will add the wait logic. 
The reason for #212 is the resource version conflict. Current changes can fix it.
Adding wait logic can avoid the loss of status information.
