### PR TITLE
Add operand status in members and fix delete status issue

### LINKED ISSUE #152: When the operator is deleted, they are not removed from status
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

When I set an operator to the absent state, after it is deleted, I found it's still in the member list of the status.

```
apiVersion: operator.ibm.com/v1alpha1
kind: OperandRequest
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"operator.ibm.com/v1alpha1","kind":"OperandRequest","metadata":{"annotations":{},"name":"common-service","namespace":"ibm-common-services"},"spec":{"services":[{"name":"ibm-cert-manager-operator","state":"present"},{"name":"ibm-mongodb-operator","state":"present"},{"name":"ibm-iam-operator","state":"present"},{"name":"ibm-management-ingress-operator","state":"absent"},{"name":"ibm-ingress-nginx-operator","state":"absent"},{"name":"ibm-metering-operator","state":"absent"},{"name":"ibm-licensing-operator","state":"absent"},{"name":"ibm-commonui-operator","state":"absent"},{"name":"ibm-healthcheck-operator","state":"present"},{"name":"ibm-auditlogging-operator","state":"absent"},{"name":"ibm-catalog-operator","state":"absent"},{"name":"ibm-platform-api-operator","state":"absent"}]}}
  selfLink: >-
    /apis/operator.ibm.com/v1alpha1/namespaces/ibm-common-services/operandrequests/common-service
  resourceVersion: '9623622'
  name: common-service
  uid: 5cfb4833-5a8a-11ea-8270-0aa228443300
  creationTimestamp: '2020-02-29T00:28:10Z'
  generation: 3
  namespace: ibm-common-services
  finalizers:
    - finalizer.request.ibm.com
spec:
  services:
    - name: ibm-cert-manager-operator
      state: absent
    - name: ibm-mongodb-operator
      state: present
    - name: ibm-iam-operator
      state: absent
    - name: ibm-management-ingress-operator
      state: absent
    - name: ibm-ingress-nginx-operator
      state: absent
    - name: ibm-metering-operator
      state: absent
    - name: ibm-licensing-operator
      state: absent
    - name: ibm-commonui-operator
      state: absent
    - name: ibm-healthcheck-operator
      state: present
    - name: ibm-auditlogging-operator
      state: absent
    - name: ibm-catalog-operator
      state: absent
    - name: ibm-platform-api-operator
      state: absent
status:
  conditions:
    - lastTransitionTime: '2020-02-28T19:31:04-05:00'
      lastUpdateTime: '2020-02-28T19:31:04-05:00'
      message: Creating subscription ibm-cert-manager-operator
      reason: Creating subscription
      status: 'True'
      type: Creating
    - lastTransitionTime: '2020-02-28T19:31:04-05:00'
      lastUpdateTime: '2020-02-28T19:31:04-05:00'
      message: Creating subscription ibm-healthcheck-operator
      reason: Creating subscription
      status: 'True'
      type: Creating
    - lastTransitionTime: '2020-02-28T19:31:04-05:00'
      lastUpdateTime: '2020-02-28T19:31:04-05:00'
      message: Creating subscription ibm-mongodb-operator
      reason: Creating subscription
      status: 'True'
      type: Creating
    - lastTransitionTime: '2020-02-28T19:31:05-05:00'
      lastUpdateTime: '2020-02-28T19:31:05-05:00'
      message: Creating subscription ibm-iam-operator
      reason: Creating subscription
      status: 'True'
      type: Creating
    - lastTransitionTime: '2020-02-28T19:37:49-05:00'
      lastUpdateTime: '2020-02-28T19:37:49-05:00'
      message: Deleting subscription ibm-cert-manager-operator
      reason: Deleting subscription
      status: 'True'
      type: Deleting
    - lastTransitionTime: '2020-02-28T19:37:50-05:00'
      lastUpdateTime: '2020-02-28T19:37:50-05:00'
      message: Deleting csv ibm-cert-manager-operator.v3.7.0
      reason: Deleting csv
      status: 'True'
      type: Deleting
    - lastTransitionTime: '2020-02-28T19:40:49-05:00'
      lastUpdateTime: '2020-02-28T19:40:49-05:00'
      message: Deleting subscription ibm-iam-operator
      reason: Deleting subscription
      status: 'True'
      type: Deleting
    - lastTransitionTime: '2020-02-28T19:40:50-05:00'
      lastUpdateTime: '2020-02-28T19:40:50-05:00'
      message: Deleting csv ibm-iam-operator.v3.5.0
      reason: Deleting csv
      status: 'True'
      type: Deleting
  members:
    - name: ibm-cert-manager-operator
      phase:
        operatorPhase: Succeeded
    - name: ibm-healthcheck-operator
      phase:
        operatorPhase: Succeeded
    - name: ibm-iam-operator
      phase:
        operatorPhase: Installing
    - name: ibm-mongodb-operator
      phase:
        operatorPhase: Succeeded
  phase: Creating
```
@DanielXLee 

**What did you expect to happen:**

The deleted operator can be removed from the `status.members`  and `status.phase` can be updated.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- ODLM version: 0.0.1
- Minikube/KIND/OCP version: OCP 4.2
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by DanielXLee**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #152

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

File: pkg/controller/operandrequest/request_status.go [hunk 1]
```diff
@@ -32,78 +33,130 @@ const (
...
+	return nil
 }
 
-func setMember(cr *operatorv1alpha1.OperandRequest, newM operatorv1alpha1.MemberStatus) {
-	pos, oldM := getMember(cr, newM.Name)
-	if oldM != nil {
-		if oldM.Phase == newM.Phase {
-			return
+func (r *ReconcileOperandRequest) getOperatorPhase(s olmv1alpha1.Subscription) (olmv1alpha1.ClusterServiceVersionPhase, error) {
+	var operatorPhase olmv1alpha1.ClusterServiceVersionPhase = ""
```
Comment (horis233) [inline pkg/controller/operandrequest/request_status.go]: Prow show.s a go-lint error 
```
pkg/controller/operandrequest/request_status.go:68:61: should drop = "" from declaration of var operatorPhase; it is the zero value (golint)
	var operatorPhase olmv1alpha1.ClusterServiceVersionPhase = ""
```

I think we should use 
```var operatorPhase olmv1alpha1.ClusterServiceVersionPhase``` 
to replace 
```var operatorPhase olmv1alpha1.ClusterServiceVersionPhase = ""```
